### ISSUE TITLE
编译到linux系统下读取不到json配置文件

### ISSUE THREAD

**Issue by FreeSaltedFish** [xxxxue/GoBuildDocsifySidebar#1]
报错如下:
unexpected end of JSON input
(0x4f1d60,0x5c19c0)

  遇到错误!!!
按回车键退出...

编译到Windows系统下倒是正常的

**Comment by xxxxue** [comment]
好像是 Config 名称变成了小写.
你把 config 目录名 和 config.json 名称中的  c 改为 大写 C,
应该就是正常了.

**Comment by xxxxue** [comment]
最新版本已修复.
